-- Make avatars and premios buckets private by replacing public SELECT policies
-- with authenticated-only policies scoped to the user's own family.
-- All reads now use short-lived signed URLs generated by resolveStorageUrl/resolveStorageUrls
-- in lib/storage.ts — no change to application code required.

-- Avatars: was readable by anyone. Now requires authentication.
DROP POLICY IF EXISTS "Avatar leitura pública" ON storage.objects;

CREATE POLICY "avatars_select_authenticated"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'avatars');

-- Premios: was readable by anyone. Now requires authentication and family membership.
DROP POLICY IF EXISTS "Premios leitura pública" ON storage.objects;

CREATE POLICY "premios_select_authenticated"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'premios'
  AND split_part(name, '/', 1) = (public.minha_familia_id())::text
);
